/* generated by generateAst.ts */

import { Token } from './token';
import { Expr } from './expr';
class Stmt {
  accept (visitor: any) {}
}

class Block extends Stmt {
  public statements: Stmt[];
  constructor (statements: Stmt[]) {
    super()
    this.statements = statements;
  }

  accept (visitor: any) {
    return visitor.visitBlockStmt(this)
  }
}

class Expression extends Stmt {
  public expression: Expr;
  constructor (expression: Expr) {
    super()
    this.expression = expression;
  }

  accept (visitor: any) {
    return visitor.visitExpressionStmt(this)
  }
}

class If extends Stmt {
  public condition: Expr;
  public thenBranch: Stmt;
  public elseBranch: Stmt;
  constructor (condition: Expr, thenBranch: Stmt, elseBranch: Stmt) {
    super()
    this.condition = condition;
    this.thenBranch = thenBranch;
    this.elseBranch = elseBranch;
  }

  accept (visitor: any) {
    return visitor.visitIfStmt(this)
  }
}

class Print extends Stmt {
  public expression: Expr;
  constructor (expression: Expr) {
    super()
    this.expression = expression;
  }

  accept (visitor: any) {
    return visitor.visitPrintStmt(this)
  }
}

class Var extends Stmt {
  public name: Token;
  public initializer: Expr;
  constructor (name: Token, initializer: Expr) {
    super()
    this.name = name;
    this.initializer = initializer;
  }

  accept (visitor: any) {
    return visitor.visitVarStmt(this)
  }
}

class While extends Stmt {
  public condition: Expr;
  public body: Stmt;
  constructor (condition: Expr, body: Stmt) {
    super()
    this.condition = condition;
    this.body = body;
  }

  accept (visitor: any) {
    return visitor.visitWhileStmt(this)
  }
}

export {
  Block,
  Expression,
  If,
  Print,
  Var,
  While,
  Stmt
}
