/* generated by generateAst.ts */

import { Expr } from './expr';
class Stmt {
  accept (visitor: any) {}
}

class Expression extends Stmt {
  public expression: Expr;
  constructor (expression: Expr) {
    super()
    this.expression = expression;
  }

  accept (visitor: any) {
    return visitor.visitingExpressionStmt(this)
  }
}

class Print extends Stmt {
  public expression: Expr;
  constructor (expression: Expr) {
    super()
    this.expression = expression;
  }

  accept (visitor: any) {
    return visitor.visitingPrintStmt(this)
  }
}

export {
  Expression,
  Print,
  Expr
}
